#!/usr/bin/make -f

APIFILES := $(notdir $(wildcard apidata/apidata-v*.json))
VERSIONS := $(patsubst apidata-%.json,%,$(APIFILES))
LATEST := v9

.PHONY: help

help: ## Display this help message
	@grep --no-filename -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'


all: proxmoxer-stubs proxmoxer_types pretty ## proxmoxer-stubs, proxmoxer_types and prettify


proxmoxer-stubs: poetry clean-stubs ## Create stubs
	cp -r src/stubs/common proxmoxer-stubs
	poetry run python3 -m stubgen --config apidata/apidata-$(LATEST).json --stubs proxmoxer-stubs/core.pyi --apiversion $(LATEST) ; \


proxmoxer_types: poetry clean-types ## Create type containers
	cp -r src/types/common proxmoxer_types
	for V in $(VERSIONS) ; do \
		cp -r src/types/each proxmoxer_types/$$V ; \
		poetry run python3 -m stubgen --config apidata/apidata-$$V.json --types proxmoxer_types/$$V/core.py --apiversion $$V ; \
	done


pretty: poetry ## Prettify autogenerated code
	poetry run black proxmoxer_types proxmoxer-stubs


test: poetry ## pytest, mypy, pyright, stubtest
	poetry run py.test --mypy
	poetry run pyright
	poetry run stubtest --ignore-missing-stub --allowlist tests/stubtest-allowlist --ignore-unused-allowlist proxmoxer


poetry:
	poetry install


clean-stubs:
	rm -rf proxmoxer-stubs


clean-types:
	rm -rf proxmoxer_types
