# This file is autogenerated by ./stubgen.py from apidata/apidata-v9.json

__license__ = "MIT"

import builtins
import typing
from functools import cached_property
from typing import Any, Literal, NotRequired, type_check_only
from _typeshed import Incomplete

import proxmoxer_types.v9 as latest

logger: Incomplete
ANYEVENT_HTTP_STATUS_CODES: Incomplete
SERVICES: Incomplete

def config_failure(message: Incomplete, *args: Incomplete) -> None: ...

class ResourceException(Exception):
    status_code: Incomplete
    status_message: Incomplete
    content: Incomplete
    errors: Incomplete
    def __init__(
        self,
        status_code: Incomplete,
        status_message: Incomplete,
        content: Incomplete,
        errors: Incomplete | None = None,
    ) -> None: ...

class AuthenticationError(Exception): ...

class ProxmoxResource:
    def __init__(self, **kwargs: Incomplete) -> None: ...
    def __getattr__(self, item: Incomplete) -> Incomplete: ...
    def url_join(self, base: Incomplete, *args: Incomplete) -> Incomplete: ...
    def __call__(self, resource_id: Incomplete | None = None) -> Incomplete: ...
    def get(self, *args: Incomplete, **params: Incomplete) -> Incomplete: ...
    def post(self, *args: Incomplete, **data: Incomplete) -> Incomplete: ...
    def put(self, *args: Incomplete, **data: Incomplete) -> Incomplete: ...
    def delete(self, *args: Incomplete, **params: Incomplete) -> Incomplete: ...
    def create(self, *args: Incomplete, **data: Incomplete) -> Incomplete: ...
    def set(self, *args: Incomplete, **data: Incomplete) -> Incomplete: ...

class ProxmoxAPI:
    def __init__(
        self,
        host: Incomplete | None = None,
        backend: str = "https",
        service: str = "PVE",
        **kwargs: Incomplete
    ) -> None: ...
    def get_tokens(self) -> Incomplete: ...
    @cached_property
    @type_check_only
    def cluster(self) -> latest.ProxmoxAPI.Cluster: ...
    @cached_property
    @type_check_only
    def nodes(self) -> latest.ProxmoxAPI.Nodes: ...
    @cached_property
    @type_check_only
    def storage(self) -> latest.ProxmoxAPI.Storage: ...
    @cached_property
    @type_check_only
    def access(self) -> latest.ProxmoxAPI.Access: ...
    @cached_property
    @type_check_only
    def pools(self) -> latest.ProxmoxAPI.Pools: ...
    @cached_property
    @type_check_only
    def version(self) -> latest.ProxmoxAPI.Version: ...
