import argparse
import json
from pathlib import Path
from . import ApiSchema

parser = argparse.ArgumentParser(
    formatter_class=argparse.ArgumentDefaultsHelpFormatter
)
parser.add_argument(
    "--config",
    type=Path,
    help="JSON schema",
    default=Path("apidata/apidata.json"),
)
parser.add_argument(
    "--stubs",
    type=Path,
    help="stub destination",
    default=Path("proxmoxer-stubs/core.pyi"),
)
parser.add_argument(
    "--types",
    type=Path,
    help="type destination, e.g. proxmoxer_types/v*/core.py",
)

args = parser.parse_args()

with args.config.open() as src:
    schema = ApiSchema(children=json.load(src))

for todo in (
    (args.stubs, schema.stubs),
    (args.types, schema.types),
):
    if todo[0]:
        with todo[0].open("w") as dst:
            print(
                f"# This file is autogenerated from {args.config}",
                file=dst,
            )
            print(file=dst)
            print(todo[1](), file=dst)
